# Generated by Django 5.1.1 on 2025-05-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("utxt", models.TextField()),
                ("email", models.TextField(default="")),
                ("ip", models.TextField(default="")),
                ("country", models.TextField(default="")),
            ],
        ),
    ]
