# Generated by Django 5.1.1 on 2025-06-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="rand",
            field=models.BigIntegerField(default=0),
        ),
    ]
