# Generated by Django 5.1.1 on 2025-06-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_news_rand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="news",
            name="ocatid",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
