# Generated by Django 5.1.1 on 2025-05-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contactform", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactform",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="contactform",
            name="time",
            field=models.TimeField(auto_now_add=True),
        ),
    ]
